### ISSUE TITLE
dist not commonjs compatible

### ISSUE THREAD

**Issue by kumavis** [Pomax/bezierjs#137] opened 2020-11-02 08:47 UTC
dist contains export statement here https://github.com/Pomax/bezierjs/blob/master/dist/bezier.js#L2236

possibly a mistake? it is possible to build "hybrid packages" that are compatible with both esm and commjs

related https://github.com/vasturiano/force-graph/issues/152

**Comment by Niek** [comment] 2020-11-02 13:42
Same problem here, can't update to 3.x until this is fixed

**Comment by Pomax** [comment] 2020-11-02 16:16
@Niek: note that nothing is "broken", and so doesn't need a "fix": this is an enhancement request. The new library was explicitly released as an ES module because everything has had support for ES modules for several versions now (all modern browsers have supported them for many, many versions, and Node's supported them for four versions, the latest 2 of which are native rather than through a runtime flag).

@kumavis if you can let me know how to make hybrid packages that work, I can look at whether that's something that can easily be added here (as far as I know the `import` and `export` keywords are illegal outside of ES module context, which is why hybrid packages weren't an option before).

**Comment by Niek** [comment] 2020-11-02 20:38
@Pomax sorry if my comment sounded too harsh. ES is definitely the way to go, but there seems to be some issue with the package being identified as CJS. I'm trying to get v3 working with https://github.com/Xetera/ghost-cursor (typescript, importing this module) but it fails with:

**Comment by danmarshall** [comment] 2020-11-02 22:23
Hi @Niek, the new bezier-js V3 is a breaking change from v2 from the TypeScript typings. So if you’re using TypeScript, you may want to keep using v2 until someone writes typings for v3.

**Comment by Pomax** [comment] 2020-11-02 22:59
Ahh, yes if we're talking about typescript, that's a kettle of fish I've no experience with.

**Comment by kumavis** [comment] 2020-11-03 05:00
> Having said that: you should not be using dist/bezier.js if you're using it as a normal dependency, [...]. For anything with build steps, you'll want to use the normal entry point that's indicated by package.json.

`dist/bezier.js` is the entry point indicated in the package.json
https://github.com/Pomax/bezierjs/blob/f23874794865e33bd154950cc66219c0fd511760/package.json#L6

**Comment by Pomax** [comment] 2020-11-03 16:05
hm, let's see what happened there.

**Comment by Pomax** [comment] 2020-11-03 16:08
Right, well: I have no idea why `lib` and `dist` were reversed, but `dist` should have been in the npmignore, not `lib`, and the main entry point should have been `lib/bezier.js`, not `dist/bezier.js`... 

Thanks for pointing this out, I've updated both files and pushed a v3.1.0 to NPM with those changes

**Comment by baughmann** [comment] 2021-11-12 18:54
Is this not typescript compatible quite yet?

**Comment by Pomax** [comment] 2021-11-14 06:18
Depends on what you mean with "compatible"? TS is a  superset of JS, so all JS is by definition TS compatible. If you mean "still does't have typing": no, because I write plain JS.

**Comment by Pomax** [comment] 2021-11-14 06:18
closing this, since a version with fix was pushed out quite a while ago.

**Closed by Pomax** 2021-11-14 06:18 UTC

**Comment by baughmann** [comment] 2021-11-14 13:23
> closing this, since a version with fix was pushed out quite a while ago.

The typings are out of date. Not your fault, like you said. But on top of that I get a “Bezier not exported from bezier-js”, even when just declaring the module in my index.d.ts 

No worries though, as I ended up just copying the functionality I needed and rewriting it a bit locally in my project and adding types.

Thank you for the awesome library btw!

**Comment by Pomax** [comment] 2021-11-14 16:47
If the library doesn't work as a normal JS import, that's 100% a bug and if you can file a bug with STR for that, that'd be appreciated.

**Comment by baughmann** [comment] 2021-11-14 16:53
@Pomax Gotcha, thank you. Maybe at some later time. However, my immediate needs are taken care of and fixing this bug will not assist me in my own project at this time. At some later point in the project, I may wish to switch back to the full lib. At that point I will assist in identifying/fixing the possible bug and updating/maintaining the typings.

**Comment by Pomax** [comment] 2021-11-14 19:35
you don't need to fix it. I just need to have an issue for it. If you know there's a problem, then at least report it so that someone can fix it. Not "for you", but "for everyone".

**Comment by baughmann** [comment] 2021-11-14 19:37
@Pomax I very well could just be doing something dumb (i.e., a bad TS config or something). I'll try to upload a minimal reproducible codebase sometime today or tomorrow and create a ticket.

**Comment by baughmann** [comment] 2021-11-14 20:22
@Pomax Please see #164
