### ISSUE TITLE
Feature Request: reverse function for .get(t)

### ISSUE THREAD

**Issue by puchm** [Pomax/bezierjs#124] opened 2020-07-01 14:36 UTC
Hi,

I have been using this library for a few weeks now and I am missing one key feature: I would like to get a t value from a given point. I am using the .project(point) method and it seems to give me a point on the curve. But if I want to use that point in further calculations, I am not sure how I could get a t value from that.

I see two solutions for this:
- An extra function that calculates the t value for a given point that is on the curve
a downside of this could be if the point is not actually on the curve or just slightly next to it.
- adjust the .project(point) function so that it returns a t value
this definitely has the downside that it could break existing software that uses this function but I think it is the cleaner solution since most things in this library work with the t values (e.g. you get a t value for the intersections) so it would make sense for this to also return a t value.

A workaround for getting the t value would probably be to make a line from the two points (result of .project(point) and parameter of it) and then use the intersects function to calculate the t value.

I have thought about trying to implement a more elegant solution by myself but I am not that familiar with bezier curves and have really appreciated being able to just rely on this library for that which I really appreciate :)
Thank you for your work!

-Moritz

**Comment by danmarshall** [comment] 2020-07-01 19:22
Hello, I think this is a duplicate of #25 . Agree it would be a good feature!

**Comment by puchm** [comment] 2020-07-01 22:36
You’re right, I did a brief search but it looks like I searched for the wrong thing since this has been requested a few times before. It didn’t get any attention for quite some time though. For now I think I will write something myself that calculates the approximate t value.

**Comment by pavel-klavik** [comment] 2020-07-02 12:41
.project function already returns a JS object containing .t which is time on the curve, and some extra stuff.

**Comment by Pomax** [comment] 2020-07-28 15:50
Also, a notes on "An extra function that calculates the t value for a given point that is on the curve a downside of this could be if the point is not actually on the curve or just slightly next to it."

There is no "the" `t` value. A single coordinate can trivially have two `t` values associated with it, or more depending on the order of the curve. The coordinate being slightly off the curve is not a problem as long as your coordinates are discrete: if an interval of `t` values all yield the same discrete coordinate, then literally of value in that interval is a valid value for the purposes of discrete graphics operations. You could try to find "the mid point" of that interval, but it's a non-linear interval and the result would be indistinguishable at the presentation level. 

As for "It didn’t get any attention for quite some time though": sadly true. I work on a lot of things, and unless someone wants to fund work on this library, it has to sit at the back of the queue while I work on things that are more important =(

When I have free time, I try to revisit the back of the queue, but I don't have a lot of free time anymore these days.

**Comment by Pomax** [comment] 2021-04-27 17:10
Closing this as the original issue is basically addressed by the fact that `project` already gives you an object with both the x/y value and the associated `t` value. I've opened https://github.com/Pomax/bezierjs/issues/152 to update the function's API page description to make this explicit.

**Closed by Pomax** 2021-04-27 17:10 UTC
