### ISSUE TITLE
add "module" into the package.json spec

### ISSUE THREAD

**Issue by jarrodek** [Pomax/bezierjs#149] opened 2021-03-20 00:42 UTC
Rollup is unable to find the module definition correctly as the `package.json` spec points to `node_modules/bezier-js/dist/bezier.common.js` which is a CJS version of the library. When you add `module` entry to the spec with `node_modules/bezier-js/dist/bezier.js` value it will solve the issue when packing with rollup.

**Comment by Pomax** [comment] 2021-04-07 15:41
I think it's time to move on to [esbuild](https://esbuild.github.io/) rather than webpack or rollup. It only knows modern ES, so no need for tricks in a package.json anymore.

**Comment by vasturiano** [comment] 2021-04-26 17:59
Hi @Pomax, thanks for putting this lib together!

I wanted to flag that there's an issue with `create-react-app` misinterpreting the way the targets are currently setup. Specifically, that bundler is unable to find out that the ES module version of this lib is at `./src/bezier.js`, and falling back to the `main` commonJS target. This in turn causes any occurrence of `import { Bezier } from "bezier-js"` in an app setup with this lib in its dependency tree fail the build.
It could be happening for other bundlers too, but this is the one that was reported in my module [force-graph](https://github.com/vasturiano/force-graph), which consumes from yours.

As @jarrodek mentioned, simply adding the conventional `"module": "./src/bezier.js"` to the package.json would fix the whole issue.
I believe this `module` field can coexist with the existing `exports` field, making it more robust and universally understood by a variety of bundlers. I know in a perfect world `exports` should be sufficient, but unfortunately we're not quite there yet.

You can see more details about the thread in the `force-graph` repo here: https://github.com/vasturiano/force-graph/issues/182

**Comment by Pomax** [comment] 2021-04-26 20:16
If you look at package.json, though, it already lists this:
```
  "type": "module",
  "exports": {
    "import": "./src/bezier.js",
    "require": "./dist/bezier.cjs"
  },
```

**Comment by Pomax** [comment] 2021-04-26 20:31
@vasturiano are you using the new v4.1.0?

**Comment by vasturiano** [comment] 2021-04-26 20:45
@Pomax yes, it's using the latest version:
https://github.com/vasturiano/force-graph/blob/dcd44014c1b03f1c946d621cc0e0bb6f92b67d65/package.json#L43

Regarding the syntax, I think it should be
```js
"module": "./src/bezier.js"
```
That's the convention for ES module bindings. Other syntaxes are probably not as widely supported.

**Comment by Pomax** [comment] 2021-04-26 23:46
_where_ though, because `module` is not a [top level property of package.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-json).

**Comment by vasturiano** [comment] 2021-04-27 00:16
@Pomax it should be right in the root level of `package.json`.

Many popular libraries use it as a way to indicate the ES module binding.
And it's the recommendation from webpack and rollup among others to use that field:
* https://webpack.js.org/guides/author-libraries/#final-steps
* https://rollupjs.org/guide/en/#compatibility
* https://github.com/rollup/rollup/wiki/pkg.module

**Comment by Pomax** [comment] 2021-04-27 23:07
Hmm, those rollup pages are from 2017, when Node's module support was an experimental feature flag that only half-worked. Things changed a lot since then, so what might _actually_ be needed here is an issue on rollup, to ask them to add support for the way module exports are indicated in a modern package.json. NPM already has a way to indicate which files are CJS vs. ESM, so if rollup doesn't tap into that, it's time we ask them to do so (in addition to consulting their own custom value).

**Comment by Pomax** [comment] 2021-04-27 23:16
In fact, I've filed https://github.com/rollup/rollup/issues/4061 to see if that's something the rollup folks have capacity for.

**Comment by vasturiano** [comment] 2021-04-28 02:48
@Pomax from my experience `rollup` is functioning and interpreting your fields correctly, at least in `rollup`'s latest version. That's why there's no issues with the build at [force-graph](https://github.com/vasturiano/force-graph), which uses rollup.

The issue found is with [create-react-app](https://github.com/facebook/create-react-app) as mentioned. Any app built using that framework will currently choke while linking `bezier-js`.

**Comment by Pomax** [comment] 2021-04-28 15:22
Then the question is "why", and really something to ask on their repo: the `module` field is not required to determine something's am es module. I would recommend filing an issue on their repo to find out why they're still not using the official Node fields when they explicitly rely on Node for the server side.

**Comment by Pomax** [comment] 2021-04-28 15:30
I'm closing this issue because it was filed to make the library support Rollup, which the current package.json in combination with the explanation in https://github.com/rollup/rollup/issues/4061 should achieve.

Feel free to file a new issue for support from other technologies, but be aware that if there is an official way to do something, I will almost certainly not be adding non-standard code for them - instead, issues should be filed with them to add support for the official way of doing things.

**Closed by Pomax** 2021-04-28 15:30 UTC

**Comment by vasturiano** [comment] 2021-04-28 21:02
Ok, I've surfaced a new issue in the `create-react-app` repo: https://github.com/facebook/create-react-app/issues/10892

Also made a basic reproducing example of the import error: https://codesandbox.io/s/create-react-app-import-bezier-js-5fxc4

I could fix this in my module by deep-linking into this package file, like `import { Bezier } from "bezier-js/src/bezier.js"`. But besides being super hacky and bound to fail whenever you update your target, it would break the CJS bindings too.

I do agree that it's better to stick with the official method of specifying this. It just gets tricky when very popular bundlers are not implementing exactly against the same standard, and it takes time for things to get to where they should be.
