### ISSUE TITLE
.offset(d) throws exception

### ISSUE THREAD

**Issue by ziggy90127** [Pomax/bezierjs#102] opened 2018-10-02 04:17 UTC
.offset(d) throws exception with certain values:
![offset3](https://user-images.githubusercontent.com/6889889/46328694-ff76b900-c5c5-11e8-8e12-4623570e7140.jpg)

If I change:
<code>new Bezier(136.65,113.85 , 215.26999999,117.74 , 293.89,113.85 , 372.07,111.69);</code>
to:
<code>new Bezier(136.65,113.85 , 215.27,117.74 , 293.89,113.85 , 372.07,111.69);</code>
Then I get:
![offset1](https://user-images.githubusercontent.com/6889889/46328748-3e0c7380-c5c6-11e8-9766-c6031f8c18af.jpg)

No exception, and seems to work, but then the last segment seems to be missing.  If I drag any coordinate, the last segment appears:
![offset2](https://user-images.githubusercontent.com/6889889/46328770-5f6d5f80-c5c6-11e8-82a3-81fb92057b8e.jpg)

A minor thing, in the function "drawCurve", the line
<code>      var p = curve.points, i;</code>
the last ", i" seems to be unused.

**Comment by Pomax** [comment] 2018-10-02 17:27
thanks, I'll have to dig into that when I have some free time again.

**Comment by debussy2k** [comment] 2018-11-15 10:43
I have the same problem. 

The code below will fail with "cannot scale this curve. Try reducing it first" error message.

```
var seg = new Bezier(56.4784042286517, 112.95538057301243, 31.180574948729816, 112.95538057742776, 9.768881274012546, 96.32488088867885, 2.578847809503432, 73.40012003978167)
seg.offset(-10)
```
I hope you have the free time by now.

**Comment by Pomax** [comment] 2018-11-15 22:16
As do I. At the earliest it'll be the weekend, but it's entirely possible I won't be able to get to this for another few weekends. If anyone is interested in doing some digging before I can get to it, have at it.

**Comment by distinctdan** [comment] 2019-02-03 03:48
So I was looking into using this library because it looks nice and does what I would need, but I'm concerned about corner cases like this one. If I'm going to include something in my project as a low level library, I need it to be pretty bulletproof. 

I was looking into contributing to attempt to fix this issue, but I'm having a bit of trouble figuring out what some of the code does because a lot of the variable names are so short they don't mean anything, or are even single letters. Is there any more documentation or comments on what they actually mean?

Take this guy for example:
```
  function getABC(n, S, B, E, t) {
    if (typeof t === "undefined") {
      t = 0.5;
    }
    var u = utils.projectionratio(t, n),
      um = 1 - u,
      C = {
        x: u * S.x + um * E.x,
        y: u * S.y + um * E.y
      },
      s = utils.abcratio(t, n),
      A = {
        x: B.x + (B.x - C.x) / s,
        y: B.y + (B.y - C.y) / s
      };
    return { A: A, B: B, C: C };
  }
```
Since it has an unguarded division by `s`, it looks like this has the potential for a divide by 0 error, but since all the variables are minified, I'm having trouble telling if that ever occurs.

**Comment by Pomax** [comment] 2019-02-07 16:10
@distinctdan please file that as a separate issue, because that has nothing to do with bug reports around offsetting and deserves its own conversation.

**Comment by distinctdan** [comment] 2019-02-11 23:24
I can file it as a separate issue, but I wanted to comment here because I was considering looking into fixing the offset issue, but a I found a lot of the codebase very difficult to read and understand.

For the fixes in general, I expect adding an `isdegenerate` property probably won't be good enough because there are a variety of different corner cases to account for. Each function would need to be  defensively coded. Like, if you're doing a division, make sure it's not 0, or if you're doing line-line intersection, account for if the lines are parallel, etc. I don't think a single check can cover all your bases.

**Comment by apodtele** [comment] 2019-10-06 14:55
I have opened a related [issue](https://github.com/Pomax/bezierinfo/issues/69). Basically, scaling is unconventional and ill-defined. The more robust approach is miter moves so that all control segments stay parallel to the original. See [here](https://math.stackexchange.com/questions/465782/control-points-of-offset-bezier-curve/467038) and [here](http://web.mit.edu/hyperbook/Patrikalakis-Maekawa-Cho/node222.html).

**Comment by rikkertkoppes** [comment] 2019-12-02 13:49
Recently added this pull request: https://github.com/Pomax/bezierjs/pull/121 does that solve your problem?

**Comment by joostdecock** [comment] 2019-12-02 14:08
@rikkertkoppes I will check tonight and report back :+1:

**Comment by joostdecock** [comment] 2019-12-02 16:54
In a first test, I am unable to reproduce this problem after the changes by @rikkertkoppes  :tada: 

While I can't speak for all possible edge-cases, I had a use-case that would consistently reproduce this issue. But now it's working as expected.

@Pomax do you plan to cut a new release with this fix? (perhaps as a `@next` or `@beta` release if you'd like to be prudent) That would be much appreciated :smiley: 

Thanks to @rikkertkoppes :pray: much appreciated!

**Comment by joostdecock** [comment] 2020-01-03 10:55
Dear @Pomax, it's been over a month since your merged the PR from @rikkertkoppes yet still no new release.

Do you think you'll be able to cut a new release soon? Is there something specific holding you back?

This fix is really important to my project. I understand you might have other priorities, but could you at least tell us what we can expect, so that we can plan accordingly (and temporary fork if it comes to that).

**Comment by joostdecock** [comment] 2020-01-04 13:45
Those who need this fixed: You can use `@freesewing/bezier-js` in the meanwhile.

**Comment by Pomax** [comment] 2020-01-05 18:50
primarily I've been on vacation. 2.4.6 is now on npm.

**Closed by Pomax** 2020-01-05 18:50 UTC
Labels: bug, help wanted

**Comment by aryzing** [comment] 2021-02-20 10:44
Hitting this issue again in 4.0.3

**Comment by Pomax** [comment] 2021-02-20 18:04
Can you please post that as a new issue?

**Comment by aryzing** [comment] 2021-02-20 20:33
Sure, continuing in #148
